title: Ramulator+DRAM Bender Tutorial @ ICS 2026
description: Cutting-Edge Infrastructures for Real and Future Memory System Evaluation @ ICS 2026
baseurl: ""
url: "https://olgunataberk.github.io/rndb-ics26"

# Theme settings
# remote_theme: pages-themes/primer@v0.6.0
theme: minima
plugins:
  - jekyll-remote-theme

# Site settings
show_downloads: false
google_analytics:

# Tutorial details
workshop:
  title: "Ramulator+DRAM Bender Tutorial"
  full_title: "Cutting-Edge Infrastructures for Real and Future Memory System Evaluation"
  date: "July 6th, 2026"
  location: "Belfast, Northern Ireland, United Kingdom"
  venue: "Assembly Buildings Conference Centre, 2-10 Fisherwick Place, Belfast, BT1 6DW"
  conference: "ICS 2026"
  conference_full: "ACM International Conference on Supercomputing"
  livestream: "TBD"
