title: Ramulator+DRAM Bender Tutorial @ MICRO 2026
description: Cutting-Edge Infrastructures for Real and Future Memory System Evaluation @ MICRO 2026
baseurl: ""
url: "https://olgunataberk.github.io/rndb-micro26"

# Theme settings
# remote_theme: pages-themes/primer@v0.6.0
theme: minima
plugins:
  - jekyll-remote-theme

# Site settings
show_downloads: false
google_analytics:

# Tutorial details
workshop:
  title: "Ramulator+DRAM Bender Tutorial"
  full_title: "Cutting-Edge Infrastructures for Real and Future Memory System Evaluation"
  date: "October 31st, 2026 (Tentative)"
  location: "Athens, Greece"
  venue: "TBA (co-located with MICRO 2026)"
  conference: "MICRO 2026"
  conference_full: "59th IEEE/ACM International Symposium on Microarchitecture"
  livestream: "TBD"
